services:
  postgres:
    image: postgres:17-alpine
    container_name: movie-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: movie_user
      POSTGRES_PASSWORD: movie_password

    ports:
      - "5433:5432"

    volumes:
      - movie_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  movie_postgres_data: